config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "reroute/authorize" => "reroute#authorize"

  resources :books do
    collection do
      get :search
    end
    resources :comments
  end
  resources :comments

  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: true }
  validates :description, presence: true
  validates :published_at, presence: true

  around_create :create_mongodb_book

  def create_comment
    abc = "New Comment"
    abc.gsub("New", "---")
  end

  def sub
    a = 1
    b = 2
    c = x + y
  end

  def add(x, y)
    x1 = x
    y1 = y

    x1 = x + 1 if x == 2

    x1 + y1
  end

  def create_mongodb_book
    ActiveRecord::Base.transaction do
      yield

      mongo_book = Mongodb::Book.first_or_initialize(book_id: id)
      mongo_book.book_id = id
      mongo_book.update(attributes.except("created_at", "updated_at", "id"))
      mongo_book.save
    end
  end
end

app/models/mongodb/book.rb
module Mongodb
  class Book
    include Mongoid::Attributes::Dynamic
    include Mongoid::Document
    include Mongoid::Timestamps

    store_in collection: "books"

    field :book_id, type: Integer
    field :title, type: String
    field :description, type: String
    field :published_at, type: DateTime
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:okta]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_sentry

  def set_sentry
    Sentry.set_user(id: 11, organization_id: 98)
    Sentry.set_extras(params: params.to_unsafe_h, url: request.original_url)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :set_sentry_extras

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    a = 0
    b = 0
    # c = a

    # raise ArgumentError.new("Exception#16")


    render json: g
  # rescue StandardError => e
  #   Sentry.with_scope do |scope|
  #     scope.set_tags(books: "books")
  #     scope.set_context(
  #       "booksinfo", {
  #         a: "Apple",
  #         b: "Ball"
  #       }
  #     )
  #     Sentry.capture_message(e.message)
  #   end
  #   render json: e.message
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :description, :published_at)
  end

  def set_sentry_extras
    Sentry.set_extras(experience_type: "apple")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    a = 1
    b = 2
    c = a + b
    render json: { c: c }
  end
end

app/controllers/reroute_controller.rb
class RerouteController < ApplicationController
  def authorize
    @url = params["url"]

    # here need to authentication process and okta session
    # can be create cross domain cookie

    final_url = prepare_callback
    redirect_to final_url, allow_other_host: true
  end

  def prepare_callback
    callback = Addressable::URI.parse(@url)
    callback.query_values = (callback.query_values || {}).merge(request.query_parameters.except(:url))
    callback.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reroute_helper.rb
module RerouteHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= book.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= book.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Published at:</strong>
    <%= book.published_at %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this book", book, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this book', edit_book_path(book), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "contents") do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :published_at %>
    <%= form.date_field :published_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing book</h1>

  <%= render "form", book: @book %>

  <%= link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Books</h1>
    <%= link_to 'New book', new_book_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="books" class="min-w-full">
    <%= render @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New book</h1>

  <%= render "form", book: @book %>

  <%= link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/books/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @book %>

    <%= link_to 'Edit this book', edit_book_path(@book), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Project23</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>